.TH "Accounts/AccountTemplate.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accounts/AccountTemplate.java \- Šablona pro uživatele\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Accounts\&.AccountTemplate\fP"
.br
.RI "Třída definující šablonu uživatele\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Accounts\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Šablona pro uživatele\&. 


.SH "AccountTemplate"
.PP
.PP
Abstraktní třída AccountTemplate Šablona pro jednotlivé uživatele bez ohledu na oprávnění\&. Implementuje interface AccountInterface
.PP
\fBViz také\fP
.RS 4
AccountInterface 
.RE
.PP

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
