.TH "Utils/BannedWords.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/BannedWords.java \- Pole zakázaných slov\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.BannedWords\fP"
.br
.RI "Abstraktní třída se zakázanými slovy\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Pole zakázaných slov\&. 


.SH "BannedWords"
.PP
.PP
Abstraktní třída se zakázanými slovy\&. 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
