.TH "Utils/BookFilter.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/BookFilter.java \- Filtr aplikovaný na vyhledávání\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.BookFilter\fP"
.br
.RI "Třída filter aplikující se na DB\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Filtr aplikovaný na vyhledávání\&. 


.SH "BookFilter"
.PP
.PP
Třída BookFilter předdefinovaný template pro filtry na DB\&. Dědí z JPanel 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
