.TH "Utils/CartItem.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/CartItem.java \- Je položka ukládaná do košíku\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.CartItem\fP"
.br
.RI "Třída vytvářející item a zobrazující se v košíku\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Je položka ukládaná do košíku\&. 


.SH "CartItem"
.PP
.PP
Třída CartItem, je položka ukládaná do košíku\&. Obsahuje jednotlivá data\&. Základ dat je poděděn z ItemTemplate 
.PP
\fBViz také\fP
.RS 4
ItemTemplate 
.RE
.PP

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
