.TH "com.Library.Utils" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.Utils
.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBBannedWords\fP"
.br
.RI "Abstraktní třída se zakázanými slovy\&. "
.ti -1c
.RI "class \fBBookFilter\fP"
.br
.RI "Třída filter aplikující se na DB\&. "
.ti -1c
.RI "class \fBCartItem\fP"
.br
.RI "Třída vytvářející item a zobrazující se v košíku\&. "
.ti -1c
.RI "class \fBDataPanel\fP"
.br
.RI "Třída zobrazující itemy\&. "
.ti -1c
.RI "class \fBFileManager\fP"
.br
.RI "Abstratkní třída pro manipulaci se soubory\&. "
.ti -1c
.RI "class \fBFormUtils\fP"
.br
.RI "Abstraktní třída s utility pro formulář\&. "
.ti -1c
.RI "class \fBItemTemplate\fP"
.br
.RI "Třída definující itemy\&. "
.ti -1c
.RI "class \fBJPanelInterface\fP"
.br
.RI "Interface k \fBJPanelTemplate\fP\&. "
.ti -1c
.RI "class \fBJPanelTemplate\fP"
.br
.RI "Třída \fBJPanelTemplate\fP slouží jako podklad do záložek\&. "
.ti -1c
.RI "class \fBListedItem\fP"
.br
.RI "Třída vykreslující item ve vyhledávání\&. "
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
