.TH "com.Library.App.ListLibraryLogic" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.App.ListLibraryLogic \- Logika vyhledávání\&.  

.SH SYNOPSIS
.br
.PP
.SS "Statické veřejné metody"

.in +1c
.ti -1c
.RI "static void \fBconcatenateData\fP (\fBListLibrary\fP listLibrary, \fBBookFilter\fP bookFilter, \fBDataPanel\fP dataPanel, boolean first)"
.br
.in -1c
.SH "Detailní popis"
.PP 
Logika vyhledávání\&. 
.SH "Dokumentace k metodám"
.PP 
.SS "static void com\&.Library\&.App\&.ListLibraryLogic\&.concatenateData (\fBListLibrary\fP listLibrary, \fBBookFilter\fP bookFilter, \fBDataPanel\fP dataPanel, boolean first)\fC [static]\fP"
Metoda pro sparcovní dat z ListLibrary
.PP
\fBParametry\fP
.RS 4
\fIlistLibrary\fP Záložka volání 
.br
\fIbookFilter\fP Filter s předvolenými daty\&. 
.br
\fIdataPanel\fP Panel s uloženými daty\&. 
.br
\fIfirst\fP Parametr, zda se jedná o první SQL command\&. 
.RE
.PP


.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
