.TH "com.Library.App.RegisterLogic" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.App.RegisterLogic \- Logika registrace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Statické veřejné metody"

.in +1c
.ti -1c
.RI "static boolean \fBregisterUser\fP (String name, String surname, String nickname, char[] password, String date)"
.br
.in -1c
.SH "Detailní popis"
.PP 
Logika registrace\&. 


.PP
\fBViz také\fP
.RS 4
\fBcom\&.Library\&.GUI\&.Register\fP
.RE
.PP
Balíček: 
.PP
\fBViz také\fP
.RS 4
\fBcom\&.Library\&.App\fP 
.RE
.PP

.SH "Dokumentace k metodám"
.PP 
.SS "static boolean com\&.Library\&.App\&.RegisterLogic\&.registerUser (String name, String surname, String nickname, char[] password, String date)\fC [static]\fP"
Metoda, která zaregistuje uživatele\&.
.PP
\fBParametry\fP
.RS 4
\fIname\fP Jméno uživatele\&. 
.br
\fIsurname\fP Přijmení uživatele\&. 
.br
\fInickname\fP nickname uživatele\&. 
.br
\fIpassword\fP Heslo uživatele\&. 
.br
\fIdate\fP Datum narození uživatele\&. 
.RE
.PP
\fBNávratová hodnota\fP
.RS 4
Vrací true/false, pokud byl nebo nebyl zaregistrován\&. 
.RE
.PP


.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
