.TH "com.Library.GUI.Menu" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.GUI.Menu \- Třída \fBGUI\fP pro \fBMenu\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dědí z bázové třídy \fBcom\&.Library\&.Utils\&.JPanelTemplate\fP\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBMenu\fP (\fBAppGUI\fP frame, boolean \fBisVisible\fP)"
.br
.ti -1c
.RI "void \fBloadCustomComponents\fP ()"
.br
.in -1c
.SS "Další zděděné členy"
.SH "Detailní popis"
.PP 
Třída \fBGUI\fP pro \fBMenu\fP\&. 


.PP
\fBViz také\fP
.RS 4
\fBJPanelTemplate\fP 
.RE
.PP

.SH "Dokumentace konstruktoru a destruktoru"
.PP 
.SS "com\&.Library\&.GUI\&.Menu\&.Menu (\fBAppGUI\fP frame, boolean isVisible)"
Konstruktor \fBMenu\fP\&. Sestaví se menu na základě uživatelského oprávnění\&.
.PP
\fBParametry\fP
.RS 4
\fIframe\fP nadřazené okno 
.br
\fIisVisible\fP viditelnost 
.RE
.PP

.SH "Dokumentace k metodám"
.PP 
.SS "void com\&.Library\&.GUI\&.Menu\&.loadCustomComponents ()"
Vzkreslení tlačítek na základě oprávnění\&. 

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
