.TH "com.Library.App.Main" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.App.Main \- Vstupní bod aplikace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Statické veřejné metody"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailní popis"
.PP 
Vstupní bod aplikace\&. 
.SH "Dokumentace k metodám"
.PP 
.SS "static void com\&.Library\&.App\&.Main\&.main (String[] args)\fC [static]\fP"
Vstupní metoda aplikace
.IP "\(bu" 2
Uloží instanci hlavního grafického rozhraní \fBAppGUI\fP
.PP
.PP
\fBViz také\fP
.RS 4
\fBAppGUI\fP 
.RE
.PP
\fBParametry\fP
.RS 4
\fIargs\fP parametry aplikace při spuštění 
.RE
.PP


.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
