.TH "com.Library.Database" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.Database
.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBDatabaseData\fP"
.br
.RI "Třída s daty k DB\&. "
.ti -1c
.RI "class \fBDatabaseManager\fP"
.br
.RI "Třída manipulující s databází\&. "
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
