.TH "com.Library.GUI.Cart" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.GUI.Cart \- Třída \fBGUI\fP pro \fBCart\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dědí z bázové třídy \fBcom\&.Library\&.Utils\&.JPanelTemplate\fP\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBCart\fP (\fBAppGUI\fP frame, boolean \fBisVisible\fP)"
.br
.ti -1c
.RI "void \fBloadCustomComponents\fP ()"
.br
.ti -1c
.RI "void \fBreloadData\fP ()"
.br
.in -1c
.SS "Statické veřejné atributy"

.in +1c
.ti -1c
.RI "static String \fBcomparing\fP = 'name'"
.br
.in -1c
.SS "Další zděděné členy"
.SH "Detailní popis"
.PP 
Třída \fBGUI\fP pro \fBCart\fP\&. 


.PP
\fBViz také\fP
.RS 4
\fBJPanelTemplate\fP 
.RE
.PP

.SH "Dokumentace konstruktoru a destruktoru"
.PP 
.SS "com\&.Library\&.GUI\&.Cart\&.Cart (\fBAppGUI\fP frame, boolean isVisible)"

.SH "Dokumentace k metodám"
.PP 
.SS "void com\&.Library\&.GUI\&.Cart\&.loadCustomComponents ()"
Metoda na načítání Komponents 
.SS "void com\&.Library\&.GUI\&.Cart\&.reloadData ()"
Přemaluje data 
.SH "Dokumentace k datovým členům"
.PP 
.SS "String com\&.Library\&.GUI\&.Cart\&.comparing = 'name'\fC [static]\fP"
Proměnná podle které se sortuje 

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
