.TH "com.Library.Database.DatabaseData" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.Library.Database.DatabaseData \- Třída s daty k DB\&.  

.SH SYNOPSIS
.br
.PP
.PP
Zděděna třídou \fBcom\&.Library\&.Database\&.DatabaseManager\fP\&.
.SS "Statické chráněné atributy"

.in +1c
.ti -1c
.RI "static String \fBdriver\fP = 'com\&.mysql\&.jdbc\&.Driver'"
.br
.ti -1c
.RI "static String \fBdatabaseURL\fP = 'jdbc:mysql://localhost:3306/library'"
.br
.ti -1c
.RI "static String \fBuser\fP = 'root'"
.br
.ti -1c
.RI "static String \fBpassword\fP = ''"
.br
.in -1c
.SH "Detailní popis"
.PP 
Třída s daty k DB\&. 
.SH "Dokumentace k datovým členům"
.PP 
.SS "String com\&.Library\&.Database\&.DatabaseData\&.databaseURL = 'jdbc:mysql://localhost:3306/library'\fC [static]\fP, \fC [protected]\fP"
Url adresa k databázi\&. 
.SS "String com\&.Library\&.Database\&.DatabaseData\&.driver = 'com\&.mysql\&.jdbc\&.Driver'\fC [static]\fP, \fC [protected]\fP"
Aktuálně nepoužívaný driver k DB\&. 
.SS "String com\&.Library\&.Database\&.DatabaseData\&.password = ''\fC [static]\fP, \fC [protected]\fP"
Heslo uživatele pro přístup do databáze\&. 
.SS "String com\&.Library\&.Database\&.DatabaseData\&.user = 'root'\fC [static]\fP, \fC [protected]\fP"
Jméno uživatele pro přístup do databáze\&. 

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
