.TH "Utils/DataPanel.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/DataPanel.java \- Třída DataPanel je pole pro načítání jednotlivých položek\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.DataPanel\fP"
.br
.RI "Třída zobrazující itemy\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Třída DataPanel je pole pro načítání jednotlivých položek\&. 


.SH "DataPanel"
.PP
.PP
Třída DataPanel je pole pro načítání jednotlivých položek\&. Dědí ze třídy JPanel 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
