.TH "Database/DatabaseData.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Database/DatabaseData.java \- Data k DB\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Database\&.DatabaseData\fP"
.br
.RI "Třída s daty k DB\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Database\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Data k DB\&. 


.SH "DatabaseData"
.PP
.PP
Abstraktní třída DatabaseData Obsahuje data připojení k databázi\&. 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
