.TH "Utils/FileManager.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/FileManager.java \- Manipulace se vstupními a výstupními soubory\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.FileManager\fP"
.br
.RI "Abstratkní třída pro manipulaci se soubory\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Manipulace se vstupními a výstupními soubory\&. 


.SH "FileManager"
.PP
.PP
Abstratkní třída pro manipulaci se soubory\&. 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
