.TH "Reference k adresáři App" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři App
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBAppGUI\&.java\fP"
.br
.RI "Hlavní frame aplikace\&. "
.ti -1c
.RI "soubor \fBListLibraryLogic\&.java\fP"
.br
.RI "Logika aplikovaná v ListLibrary\&. "
.ti -1c
.RI "soubor \fBLoginLogic\&.java\fP"
.br
.RI "Logika aplikovaná v Login\&. "
.ti -1c
.RI "soubor \fBMain\&.java\fP"
.br
.RI "Vstupní bod aplikace\&. "
.ti -1c
.RI "soubor \fBOrderLogic\&.java\fP"
.br
.RI "Logika aplikovaná v Order\&. "
.ti -1c
.RI "soubor \fBRegisterLogic\&.java\fP"
.br
.RI "Logika aplikovaná v Register\&. "
.in -1c
