.TH "Reference k adresáři Utils" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři Utils
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBBannedWords\&.java\fP"
.br
.RI "Pole zakázaných slov\&. "
.ti -1c
.RI "soubor \fBBookFilter\&.java\fP"
.br
.RI "Filtr aplikovaný na vyhledávání\&. "
.ti -1c
.RI "soubor \fBCartItem\&.java\fP"
.br
.RI "Je položka ukládaná do košíku\&. "
.ti -1c
.RI "soubor \fBDataPanel\&.java\fP"
.br
.RI "Třída DataPanel je pole pro načítání jednotlivých položek\&. "
.ti -1c
.RI "soubor \fBFileManager\&.java\fP"
.br
.RI "Manipulace se vstupními a výstupními soubory\&. "
.ti -1c
.RI "soubor \fBFormUtils\&.java\fP"
.br
.RI "Doplňuje formůláře o některé detaily\&. "
.ti -1c
.RI "soubor \fBItemTemplate\&.java\fP"
.br
.RI "Je šablona pro itemy\&. "
.ti -1c
.RI "soubor \fBJPanelInterface\&.java\fP"
.br
.RI "Interface zařizující nutnou metodu loadCustomComponents() "
.ti -1c
.RI "soubor \fBJPanelTemplate\&.java\fP"
.br
.RI "Třída JPanelTemplate slouží jako podklad do záložek\&. "
.ti -1c
.RI "soubor \fBListedItem\&.java\fP"
.br
.RI "Je item vypisující se ve vyhledávání\&. "
.in -1c
