.TH "Reference k adresáři GUI" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři GUI
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBCart\&.java\fP"
.br
.RI "GUI Cart\&. "
.ti -1c
.RI "soubor \fBListLibrary\&.java\fP"
.br
.RI "GUI ListLibrary\&. "
.ti -1c
.RI "soubor \fBLogin\&.java\fP"
.br
.RI "GUI Login\&. "
.ti -1c
.RI "soubor \fBMenu\&.java\fP"
.br
.RI "GUI Menu\&. "
.ti -1c
.RI "soubor \fBOrder\&.java\fP"
.br
.RI "GUI Order\&. "
.ti -1c
.RI "soubor \fBRegister\&.java\fP"
.br
.RI "GUI Register\&. "
.in -1c
