.TH "Reference k adresáři Database" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři Database
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBDatabaseData\&.java\fP"
.br
.RI "Data k DB\&. "
.ti -1c
.RI "soubor \fBDatabaseManager\&.java\fP"
.br
.RI "Třída pro práci se soubory\&. "
.in -1c
