.TH "Utils/ItemTemplate.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/ItemTemplate.java \- Je šablona pro itemy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.ItemTemplate\fP"
.br
.RI "Třída definující itemy\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Je šablona pro itemy\&. 


.SH "ItemTemplate"
.PP
.PP
Třída ItemTemplate je poděděna z JPanel 
.PP
\fBViz také\fP
.RS 4
JPanel a implentuje Interface MouseListener 
.PP
MouseListener 
.RE
.PP

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
