.TH "Utils/JPanelInterface.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/JPanelInterface.java \- Interface zařizující nutnou metodu loadCustomComponents()  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Utils\&.JPanelInterface\fP"
.br
.RI "Interface k \fBJPanelTemplate\fP\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Utils\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Interface zařizující nutnou metodu loadCustomComponents() 


.SH "JPanelInterface"
.PP
.PP
Interface zařizující nutnou metodu \fBloadCustomComponents()\fP Implementace v JPanelTemplate 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
