.TH "GUI/ListLibrary.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI/ListLibrary.java \- GUI ListLibrary\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.GUI\&.ListLibrary\fP"
.br
.RI "Třída \fBGUI\fP pro \fBListLibrary\fP\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.GUI\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
GUI ListLibrary\&. 


.SH "ListLibrary"
.PP
.PP
Třída ListLibrary poděděná z třídy JPanelTemplate Grafické rozhraní pro vyhledávání v databázi\&. 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
