.TH "App/LoginLogic.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App/LoginLogic.java \- Logika aplikovaná v Login\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.App\&.LoginLogic\fP"
.br
.RI "Logika přihlášení\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.App\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Logika aplikovaná v Login\&. 


.SH "LoginLogic"
.PP
.PP
Abstraktní třída LoginLogic Logika tabu Login
.PP
\fBViz také\fP
.RS 4
Login 
.RE
.PP

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
