.TH "Accounts/SuperUser.java" 3 "ne 17. kvě 2020" "Version 1" "Dokumentace BookLibrary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accounts/SuperUser.java \- Definice SuperUser\&.  

.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBcom\&.Library\&.Accounts\&.SuperUser\fP"
.br
.RI "Třída definující Super uživatele\&. "
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBcom\&.Library\&.Accounts\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Definice SuperUser\&. 


.SH "SuperUser"
.PP
.PP
Třída SuperUser pro uživatele s daným opravněním Dědí z abstraktní třídy AccountTemplate 
.PP
\fBViz také\fP
.RS 4
SuperUser 
.RE
.PP

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Dokumentace BookLibrary\&.
